### ISSUE TITLE
Cannot create simulation with 0 agent/object

### ISSUE THREAD

**Issue by Marsolo1** [clement-moulin-frier/vivarium#53]
### Description
Using the launch command for the server with `--n_agents 0` or `--n_objects 0` raises an error.
```
Traceback (most recent call last):
  File "/Users/martial/vivarium/scripts/run_server.py", line 62, in <module>
    state = set_state_from_config_dict({StateType.AGENT: agent_configs,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/martial/vivarium/vivarium/controllers/converters.py", line 221, in set_state_from_config_dict
    params = configs[0].param_names()
             ~~~~~~~^^^
IndexError: list index out of range
```
### Steps to Reproduce
Start the server with `--n_agents 0`

### Environment (Optional)
- OS: MacOS
- Browser: Firefox
- Python Version: 3.11

**Comment by corentinlger** [comment]
Command doesn't exist anymore in current project.
